// Generated by prepare-release.mjs; cache one complete release.
const prefix = 'birthday-zbl:' + self.registration.scope + ':';
const cacheName = prefix + "2026-09-20T15:18:22.770Z";
const files = ["assets/index-CSYLXUDC.js","assets/index-DaW9IdWL.css","icon.svg","./","licenses/GPL-3.0.txt","licenses/LGPL-3.0.txt","licenses/fflate-MIT.txt","licenses/galaxy-upstream.txt","licenses/three-MIT.txt","manifest.webmanifest","source.html","third-party-notices.txt"].map(file => new URL(file, self.registration.scope).href);
self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(cacheName);
    await cache.addAll(files);
    // Some hosts redirect source.html to /source. A navigation cannot reuse a
    // redirected cached response. Preserve its content as a plain response.
    for (const url of files) {
      const response = await cache.match(url, { ignoreVary: true });
      if (!response?.redirected) continue;
      const headers = new Headers(response.headers);
      headers.delete('content-encoding');
      headers.delete('content-length');
      await cache.put(url, new Response(response.body, { status: response.status, statusText: response.statusText, headers }));
    }
    // Recover the first Cloudflare preview, whose cached /index.html had a
    // redirect response and could not be used for a browser navigation.
    for (const key of await caches.keys()) {
      if (!key.startsWith(prefix) || key === cacheName) continue;
      const oldIndex = await (await caches.open(key)).match(new URL('index.html', self.registration.scope).href, { ignoreVary: true });
      if (oldIndex?.redirected) { await self.skipWaiting(); break; }
    }
  })());
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith(prefix) && key !== cacheName) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});
self.addEventListener('message', event => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});
self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;
  event.respondWith((async () => {
    const cache = await caches.open(cacheName);
    // These assets are identical for every visitor. Ignore the dev server's Vary: Origin.
    const cached = await cache.match(request, { ignoreSearch: true, ignoreVary: true });
    if (cached) return cached;
    if (request.mode === 'navigate' && (new URL(request.url).pathname.endsWith('/') || new URL(request.url).pathname.endsWith('/index.html'))) {
      const index = await cache.match(self.registration.scope, { ignoreVary: true });
      if (index) return index;
    }
    return fetch(request);
  })());
});
